// flow-typed signature: e0a141e1726bfbdec98bb018e0adf82b
// flow-typed version: <<STUB>>/@types/chai_v^4.2.0/flow_v0.134.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/chai'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/chai' {
  declare module.exports: any;
}
