// flow-typed signature: 6f00f13d605ff4708f94226ffec40c37
// flow-typed version: <<STUB>>/@types/enzyme_v^3.10.3/flow_v0.134.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/enzyme'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/enzyme' {
  declare module.exports: any;
}
