// flow-typed signature: ca8282af56196771bb8f9e78d63f6f8d
// flow-typed version: <<STUB>>/@types/mocha_v^5.2.7/flow_v0.134.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/mocha'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/mocha' {
  declare module.exports: any;
}
