// flow-typed signature: f397dc8b14b558a2b2d68dc98f28b0f0
// flow-typed version: <<STUB>>/@types/node_v^12.12.6/flow_v0.134.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/node' {
  declare module.exports: any;
}
