// flow-typed signature: e973e2bc63812ef63e0a2c51348b3425
// flow-typed version: <<STUB>>/@types/react_v^16.9.11/flow_v0.134.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react' {
  declare module.exports: any;
}
