// flow-typed signature: 6fa8a8dd70ae49d3658e2686cb3150b4
// flow-typed version: <<STUB>>/@jedwards1211/eslint-config-typescript_v^1.0.0/flow_v0.134.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@jedwards1211/eslint-config-typescript'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@jedwards1211/eslint-config-typescript' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@jedwards1211/eslint-config-typescript/index' {
  declare module.exports: $Exports<'@jedwards1211/eslint-config-typescript'>;
}
declare module '@jedwards1211/eslint-config-typescript/index.js' {
  declare module.exports: $Exports<'@jedwards1211/eslint-config-typescript'>;
}
